language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t k8s/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true k8s/react-test npm test -- --coverage

after_success:
  - docker build -t k8s/multi-client ./client
  - docker build -t k8s/multi-nginx ./nginx
  - docker build -t k8s/multi-server ./server
  - docker build -t k8s/multi-worker ./worker
  
#log into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push the build images to docker hub
 - docker push k8s/multi-client
 - docker push k8s/multi-nginx
 - docker push k8s/multi-server
 - docker push k8s/multi-workder
