language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t k8s/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true k8s/react-test npm test -- --coverage

after_success:
  - docker build -t d4rk8s/multi-client ./client
  - docker build -t d4rk8s/multi-nginx ./nginx
  - docker build -t d4rk8s/multi-server ./server
  - docker build -t d4rk8s/multi-worker ./worker
  
  
#log into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push the build images to docker hub
  - docker push d4rk8s/multi-client
  - docker push d4rk8s/multi-nginx
  - docker push d4rk8s/multi-server
  - docker push d4rk8s/multi-worker
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: k8sDocker
  env: K8sDocker-env
  bucket_name: elasticbeanstalk-us-east-1-908665615728
  bucket_path: K8sDocker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
